apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-app
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: flux-app
  template:
    metadata:
      labels:
        app: flux-app
    spec:
      containers:
      - name: flux-app
        image: 1292003/shahidul:latest
        ports:
        - containerPort: 8080
