apiVersion: v1
kind: Service
metadata:
  name: flux-app
  labels:
    app: flux-app
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30031
    targetPort: 80
    protocol: TCP
  selector:
    app: flux-app
