apiVersion: v1
kind: Service
metadata:
  name: testweb
  labels:
    app: testweb
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30032
    targetPort: 80
    protocol: TCP
  selector:
    app: sample-app

